AssociationBids.Portal/Controllers/EmailTempletController.cs
using AssociationBids.Portal.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using EmailFilterModel = AssociationBids.Portal.Model.EmailFilterModel;

namespace AssociationBids.Portal.Controllers
{
    public class EmailTemplateController : Controller
    {
        private readonly AssociationBids.Portal.Service.Base.Interface.IEmailTemplateService __eMailTemlateService;
        public EmailTemplateController(AssociationBids.Portal.Service.Base.Interface.IEmailTemplateService  emailTempletService )
        {
            this.__eMailTemlateService  = emailTempletService ;
        }
        public ActionResult EmailTemplateList()
        {
            try
            {
                IList<EmailTemplateModel> lEmailTemplate = null;
                lEmailTemplate = __eMailTemlateService.GetAll();
                return View(lEmailTemplate);
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
                return View();
            }
            
        }
        
        public JsonResult IndexreEmailTmpPaging(Int64 PageSize, Int64 PageIndex, string Search, String Sort,string EmailTite,string EmailType)
        {
            List<EmailTemplateModel> lstEmailTemplate = null;
            lstEmailTemplate = __eMailTemlateService.SearchUser(PageSize, PageIndex, Search.Trim(), Sort, EmailTite, EmailType);
            return Json(lstEmailTemplate, JsonRequestBehavior.AllowGet);
        }
        public void FillEmailType()
        {
            try
            {
                IList<LookUpModel> lLookUp = null;
                lLookUp = __eMailTemlateService.GetAllTitle();
                List<System.Web.Mvc.SelectListItem> lLookUpList = new List<System.Web.Mvc.SelectListItem>();
                System.Web.Mvc.SelectListItem sli2 = new System.Web.Mvc.SelectListItem();
                sli2.Text = "--Please Select--";
                sli2.Value = "0";
                lLookUpList.Add(sli2);
                for (int i = 0; i < lLookUp.Count; i++)
                {
                    System.Web.Mvc.SelectListItem sli = new System.Web.Mvc.SelectListItem();
                    sli.Text = Convert.ToString(lLookUp[i].Title);
                    sli.Value = Convert.ToString(lLookUp[i].LookUpKey);
                    lLookUpList.Add(sli);
                }
                ViewBag.lststate = lLookUpList;
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
            }

        }
        // GET: EmailTemplet
        public ActionResult EmailTemplateAdd()
        {
            //EmailTemplateModel EmailTmpDirectory = new EmailTemplateModel();
            //EmailTmpDirectory.Body = "a";
            FillEmailType();
            return View();
        }
        
        [HttpPost]
        public ActionResult EmailTemplateAdd(EmailTemplateModel  collection, HttpPostedFileBase[] files)
        {
            try
            {
                    Int64 value = 0;
                    value = __eMailTemlateService.Insert(collection);
                    if (value != 0)
                    {
                        TempData["Sucessmessage"] = "Record has been inserted successfully.";
                    }
                    else
                    {
                        ViewData["Errormessage"] = "Error";
                    }
                    return RedirectToAction("EmailTemplateList");
                
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
                return View("EmailTemplateList");
            }
        }

        public ActionResult EmailTemplateView(int EmailTemplateKey)
        {
            List<EmailTemplateModel> EmailTmpList = null;
            EmailTemplateModel EmailTmpDirectory = new EmailTemplateModel();
            EmailTmpDirectory = __eMailTemlateService.GetDataViewEdit(EmailTemplateKey);

            EmailTmpDirectory.Body = EmailTmpDirectory.Body.Replace("&nbsp;", " ");
            return View(EmailTmpDirectory);
        }
       

        // GET: EditEmailTemplate
        public ActionResult EmailTemplateEdit(int EmailTemplateKey)
        {
            try
            {
                IList<LookUpModel> lLookUp = null;

                lLookUp = __eMailTemlateService.GetAllTitle();
                List<System.Web.Mvc.SelectListItem> lLookUpList = new List<System.Web.Mvc.SelectListItem>();
                System.Web.Mvc.SelectListItem sli2 = new System.Web.Mvc.SelectListItem();
                sli2.Text = "--Please Select--";
                sli2.Value = "0";
                lLookUpList.Add(sli2);
                for (int i = 0; i < lLookUp.Count; i++)
                {
                    System.Web.Mvc.SelectListItem sli = new System.Web.Mvc.SelectListItem();
                    sli.Text = Convert.ToString(lLookUp[i].Title);
                    sli.Value = Convert.ToString(lLookUp[i].LookUpKey);
                    lLookUpList.Add(sli);
                }
                ViewBag.lstlookup = lLookUpList;
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
            }
                EmailTemplateModel resources = null;
                resources = __eMailTemlateService.GetDataViewEdit(EmailTemplateKey);
                return View(resources);
            }

        [HttpPost]
        public ActionResult EmailTemplateEdit(int EmailTemplateKey, EmailTemplateModel  collection)
        {
            try
            {
             
                Int64 value = 0;
                EmailTemplateModel resources = null;
                    resources = __eMailTemlateService.GetDataViewEdit(EmailTemplateKey);              
                  
                    
                value = __eMailTemlateService.EmailTempletEdit(collection,resources.lookUpType);
                    if (value == 0)
                    {
                        TempData["SuccessMessage"] = "Record has been  updated successfully.";
                    }
                    else
                    {
                        ViewData["ErrorMessage"] = "Error";
                    }

                return RedirectToAction("EmailTemplateView", new { EmailTemplateKey });
        
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
                return View("EmailTemplateList");
            }
        }

        public ActionResult EmailTempletupdates(int EmailTemplateKey)
        {
            try
            {
                IList<LookUpModel> lLookUp = null;
                lLookUp = __eMailTemlateService.GetAllTitle();
                List<System.Web.Mvc.SelectListItem> lLookUpList = new List<System.Web.Mvc.SelectListItem>();
                System.Web.Mvc.SelectListItem sli2 = new System.Web.Mvc.SelectListItem();
                sli2.Text = "--Please Select--";
                sli2.Value = "0";
                lLookUpList.Add(sli2);
                for (int i = 0; i < lLookUp.Count; i++)
                {
                    System.Web.Mvc.SelectListItem sli = new System.Web.Mvc.SelectListItem();
                    sli.Text = Convert.ToString(lLookUp[i].Title);
                    sli.Value = Convert.ToString(lLookUp[i].LookUpKey);
                    lLookUpList.Add(sli);
                }
                ViewBag.lststate = lLookUpList;
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
            }
          

            return View();
        }
        [HttpPost]
        public ActionResult EmailTempletupdates(int EmailTemplateKey, EmailTemplateModel  collection)
        {
            try
            {
                Int64 value = 0;
                value = __eMailTemlateService.EmailTempletupdates(collection);
                if (value != 0)
                {
                    TempData["Sucessmessage"] = "Record has been inserted successfully.";
                }
                else
                {
                    ViewData["Errormessage"] = "Error";
                }
                return RedirectToAction("EmailTemplateList");

            }
            catch (Exception ex)
            {
                return View("EmailTemplateList");
            }
        }

        public ActionResult Delete(Int32 EmailTemplateKey)
        {
            try
            {
                bool Status = false;
                Status = __eMailTemlateService.Remove(EmailTemplateKey);
                if (Status == true)
                {
                    TempData["Sucessmessage"] = "Record has been deleted successfully.";
                }
                else
                {
                    ViewData["Errormessage"] = "Error";
                }
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
            }
           
            return RedirectToAction("EmailTemplateList");

        }
       
    }
}

AssociationBids.Portal/Views/EmailTemplate/EmailTemplateAdd.cshtml
@model AssociationBids.Portal.Model.EmailTemplateModel

@{
    ViewBag.Title = "EmailTemplateAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>EmailTemplateAdd</h2>

<link href="~/js/jquery.tagsinput.css" rel="stylesheet" />
<script src="~/ckeditor/ckeditor.js"></script>
<script src="~/js/jquery.tagsinput.js"></script>

<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script src="https://cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .error {
        color: red;
    }
</style>
<!-- app-content-->
<div class="app-content  my-3 my-md-5">
    <div class="side-app">

        <!-- page-header -->
        <div class="page-header">
            <ol class="breadcrumb">
                <!-- breadcrumb -->
                <li class="breadcrumb-item"><a href="EmailTemplateList">Email Templates</a></li>
                <li class="breadcrumb-item active" aria-current="page">Add Email Templates</li>
            </ol><!-- End breadcrumb -->
        </div> <div class="alert alert-danger" id="Error" style="display:block; margin-top: 20px;">
            <strong><span class="errormessage"></span></strong>
        </div>

        <!-- End page-header -->

        @using (Html.BeginForm("EmailTemplateAdd", "EmailTemplate", FormMethod.Post, new { enctype = "multipart/form-data" }))

        {
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        <div class="card-body">

                            <div class="form-div">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label class="form-label">Email Title @Html.ValidationMessageFor(model => model.EmailTitle, "*", new { @class = "text-danger" })  </label>
                                            @Html.EditorFor(model => model.EmailTitle, new { htmlAttributes = new { @class = "form-control", @tabindex = "1", autocomplete = "off", placeholder = "Email Title" } })
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="form-label">
                                                Email Type
                                                @Html.ValidationMessageFor(model => model.lookUpType, "*", new { @class = "text-danger" })
                                            </label>
                                            @Html.DropDownListFor(model => model.lookUpType, new SelectList(ViewBag.lststate, "Value", "Text"), new { @data_rel = "Choose_one", @class = "form-control", placeholder = "Please Select..." })

                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="form-label">
                                                Subject
                                                @Html.ValidationMessageFor(model => model.EmailSubject, "*", new { @class = "text-danger" })
                                            </label>
                                            @Html.EditorFor(model => model.EmailSubject, new { htmlAttributes = new { @class = "form-control", @tabindex = "1", autocomplete = "off", placeholder = "Email Subject" } })
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="form-label">
                                                Body
                                               
                                            </label>
                                            @Html.TextAreaFor(model => model.Body, new { @class = "form-control ", placeholder = "EmailSubject" })
                                            <script>
                                                CKEDITOR.replace('Body');
                                            </script>
                                        </div>
                                    </div>

                                </div><!-- end of row -->
                                <hr />

                                <div class="button-row d-flex mt-4">
                                    <a href="@Request.UrlReferrer" class="btn btn-default" title="Cancel">Cancel</a>
                                    @*<button class="btn btn-info ml-auto js-btn-next" id="btnsubmit" type="button" title="Next">Next <i class="fe fe-chevron-right"></i></button>*@
                                    <input t class="btn btn-primary ml-auto" id="btnsubmit" type="submit" onclick="return validation()" title="Save" value="Save" /><i class="fa fa-loppy-o"></i>
                                </div>

                            </div><!-- end of form-div  -->

                        </div><!--end of card body -->
                    </div>
                </div>
            </div>
        }
    </div><!--End side app-->
    <!-- Right-sidebar-->
    <!--footer-->
    <footer class="footer">
        <div class="container">
            <div class="row align-items-center flex-row-reverse">
                <div class="col-lg-12 col-sm-12   text-center">
                    Copyright © 2020 Association Bids. All rights reserved.
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer-->

</div>
<!-- End app-content-->
<!-- End Page -->
<!-- Back to top -->
<a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>



<!-- Custom js-->
<script src="../assets/js/custom.js"></script>

<script type="text/javascript">
    //tinymce.init({ selector: 'textarea' });
    $(document).ready(function () {
        $("#EmailT").closest('li').addClass('active');
        $("#EmailT1").addClass('active');
        $(".advance_search").click(function () {
            $("#advancesearch3").toggle(500);
        });
        $(".overlayclose").click(function () {
            $("#advancesearch3").hide();
        });
    });
    $(document).ready(function () {
        $('#loader').show();
        $('.errormessage').html('');
        $('#Error').hide();

        $('#loader').hide();

    });
    function validation() {
        debugger;
        //("#bfnmkdbfndkbf").val(); 
        var sd = $("#tinymce").innerText;
        //alert(sd);
        $('#loader').show();
        //alert($('#Body').val());
        $('.errormessage').html('');

        if ($('#EmailTitle').val() == "") {
            $('.errormessage').html('Please Enter Email Title.');
            $('#Error').show();
            $('#EmailTitle').focus();
            $(window).scrollTop(0);
            return false;
        }
        if ($('#lookUpType').val() == "0") {
            $('.errormessage').html('Please Select Email Type.');
            $('#Error').show();
            $(window).scrollTop(0);
            return false;
        }

        if ($('#EmailSubject').val() == "") {
            $('.errormessage').html('Please Enter Email Subject.');
            $('#Error').show();
            $('#EmailSubject').focus();
            $(window).scrollTop(0);
            return false;
        }

        //if ($('#Body').val() == "") {
        //    $('.errormessage').html('Please Enter Body.');
        //    $('#Error').show();
        //    $('#Body').focus();
        //    $(window).scrollTop(0);
        //    return false;
        //}
        $('#loader').hide();

        return true;
    }

    function Clear() {

        document.getElementById("EmailTitle").value = "";
        document.getElementById("lookUpType").value = "Please Select";
        document.getElementById("EmailSubject").value = "";
        document.getElementById("Body").value = "";
        $('.field-validation-error').html("");
    }


    $("#btnadd").click(function () {
        $("#managerdiv table tbody tr:not(:first)").remove();
        var SelectedManager = $("#ManagerChoosen option:selected").map(function () {
            var cln = $("#managerdiv table tbody tr:eq(0)").clone(true);
            $(".manspan", cln).html($(this).text());
            $("#managerdiv table").append(cln);

        }).get();
        $("#managerdiv table tbody tr:eq(0)").hide();


        if ($('#ManagerChoosen_chosen').find('.chosen-choices').find('.search-choice').length == 0) {
            $('.errormessage').html('Please select manager.');
            $('#Errormanager').show();
            return false;
        }
        else {
            var SelectedManager = $("#ManagerChoosen option:selected").map(function () {
                return $(this).val();
            }).get().join(',');
            $('#ResourceKey').val(SelectedManager);
        }

    });

    $('#UserId').change(function () {
        // Get Dropdownlist seleted item text
        $("#lbltxt").text($("#UserId option:selected").text());
        // Get Dropdownlist selected item value
        $("#lblid").text($("#UserId").val());
    });

    debugger

</script>

AssociationBids.Portal/Views/EmailTemplate/EmailTemplateView.cshtml
@model AssociationBids.Portal.Model.EmailTemplateModel
@{
    ViewBag.Title = "EmailTemplateView";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string Errormessage = Convert.ToString(TempData["ErrorMessage"]);
    string SuccessMessage = Convert.ToString(TempData["SuccessMessage"]);
}
}
@using System.Text.RegularExpressions;

@helper StripHTML(string input)
{
    if (!string.IsNullOrEmpty(input))
    {
        input = Regex.Replace(input, "<.*?>", String.Empty);
        <span>@input</span>
    }
}
<h2>EmailTemplateView</h2>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Content/themes/assets/js/vendors/jquery-3.2.1.min.js"></script>

<!--sidemenu end-->
<!-- app-content-->
<div class="app-content  my-3 my-md-5">
    <div class="side-app">

        <!-- page-header -->
        <div class="page-header">
            <ol class="breadcrumb">
                <!-- breadcrumb -->
                <li class="breadcrumb-item"><a href="EmailTemplateList">Email Template</a></li>
                <li class="breadcrumb-item active" aria-current="page">View Email Template</li>
            </ol><!-- End breadcrumb -->

        </div>
        <!-- End page-header -->
        @if (!string.IsNullOrEmpty(Errormessage))
        {
            <p class="alert alert-success alert-dismissible">
                @Errormessage
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            </p>
        }
        @if (!string.IsNullOrEmpty(SuccessMessage))
        {
            <p class="alert alert-success alert-dismissible">
                @SuccessMessage
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            </p>
        }

        <div class="row">
            <div class="col-12">
                <div class="card">

                    <div class="card-body">

                        @*<div class="row">
                            <div class="button-row d-flex mt-4">
                                <a onclick=" EditPage();" class="btn btn-primary ml-auto  pull-right" title="Edit"><i class="fa fa-pencil"></i> Edit</a>
                            </div>
                        </div>*@

                        <div class="card-header">
                            <h3 class="card-title">Email Template Detail</h3>
                            <div class="card-options">
                                <a onclick=" EditPage();" class="btn btn-primary ml-auto text-white pull-right" title="Edit"><i class="fa fa-pencil"></i> Edit</a>
                                <a style="margin-left: 10px;" href="#" class="card-options-collapse mr-2" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                            </div>

                        </div>
                        <hr />

                        <div class="form-div">
                            <div class="row">
                                @Html.HiddenFor(item => Model.EmailTemplateKey)
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="form-label">Title</label>
                                        @Html.DisplayFor(item => Model.EmailTitle)
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="form-label">Email Type</label>
                                        @Html.DisplayFor(item => item.Title)
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="form-label">Subject</label>
                                        @Html.DisplayFor(item => item.EmailSubject)
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-label">Body</label>
                                        @StripHTML(Model.Body)

                                    </div>
                                </div>

                            </div><!-- end of row -->

                            <hr />
                            @*<div class="button-row d-flex mt-4">
                                <a href="@Request.UrlReferrer" class="btn btn-default" title="Cancel">Cancel</a>
                            </div>*@
                        </div><!-- end of form-div  -->

                    </div><!--end of card body -->
                </div>
            </div>
        </div>
    </div><!--End side app-->
    <!--footer-->
    <footer class="footer">
        <div class="container">
            <div class="row align-items-center flex-row-reverse">
                <div class="col-lg-12 col-sm-12   text-center">
                    Copyright © 2020 Association Bids. All rights reserved.
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer-->

</div>
<!-- Custom js-->
<script src="../assets/js/custom.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        //$("#EmailT").closest('li').addClass('active');
        //$("#EmailT1").addClass('active');
        SetActiveMenu($("#EmailT"), false);
        $(".advance_search").click(function () {
            $("#advancesearch3").toggle(500);
        });
        $(".overlayclose").click(function () {
            $("#advancesearch3").hide();
        });
    });
    function EditPage() {

        window.location.href = 'EmailTemplateEdit?EmailTemplateKey=' + $("#EmailTemplateKey").val();

    }
</script>