AssociationBids.Portal/Controllers/AgreementController.cs
using AssociationBids.Portal.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using EmailFilterModel = AssociationBids.Portal.Model.EmailFilterModel;

namespace AssociationBids.Portal.Controllers
{
    public class AgreementController : Controller
    {
        private readonly AssociationBids.Portal.Service.Base.Interface.IAgreementService __aGreementService;
        public AgreementController(AssociationBids.Portal.Service.Base.Interface.IAgreementService AgreementService)
       
        {
            this.__aGreementService = AgreementService;
        }
        public ActionResult AgreementList()
        {
            try
            {
                IList<AgreementModel> lAgreement = null;
                lAgreement = __aGreementService.GetAll();
                return View(lAgreement);
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
                return View();
            }
            
        }
        public JsonResult IndexreAgreementPaging(Int64 PageSize, Int64 PageIndex, string Search, String Sort)
        {
            
                List<AgreementModel> lstEmailTemplate = null;
                lstEmailTemplate = __aGreementService.SearchUser(PageSize, PageIndex, Search.Trim(), Sort);
                return Json(lstEmailTemplate, JsonRequestBehavior.AllowGet);
        }

        public JsonResult IndexreAgreementPagingForAdvancedSearch(Int64 PageSize, Int64 PageIndex, string Search, string Status,String Sort)
        {

            List<AgreementModel> lstEmailTemplate = null;
            lstEmailTemplate = __aGreementService.AdvancedSearchAgreement(PageSize, PageIndex, Search.Trim(), Status.Trim(), Sort);
            return Json(lstEmailTemplate, JsonRequestBehavior.AllowGet);
        }

        // GET: Agreement
        public ActionResult AgreementAdd()
        {
            //list of Status
            FillStatus();
            return View();
        }
        [HttpPost]
        public ActionResult AgreementAdd(AgreementModel collection, HttpPostedFileBase[] files)
        {
            try
            {
                    int value = 0;
                    value = __aGreementService.Insert(collection);
                    if (value != 0)
                    {
                        TempData["Sucessmessage"] = "Record has been inserted successfully.";
                    AgreementModel Agreementlist = new AgreementModel();
                    int AgreementKey = value;
                    Agreementlist = __aGreementService.GetDataViewEdit(AgreementKey);
                    return View("AgreementView", Agreementlist);
                }
                    else
                    {
                        ViewData["Errormessage"] = "Error";
                    }
                
                return RedirectToAction("AgreementList");

            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
                return View("AgreementList");
            }
        }
        public ActionResult AgreementView(int AgreementKey )
        {
            List<AgreementModel> AgreementList = null;
            AgreementModel Agreementlist = new AgreementModel();
            Agreementlist = __aGreementService.GetDataViewEdit(AgreementKey);
            Agreementlist.Description = Agreementlist.Description.Replace("\r\n", "<br>");
             
            return View(Agreementlist);
        }
        [HttpPost]
        public ActionResult AgreementView(AgreementModel collection)
        {
            try
            {
                Int64 value = 0;


                value = __aGreementService.AgreementEdit(collection);
                if (value != 0)
                {
                    TempData["SuccessMessage"] = "Record has been Updated successfully.";
                }
                else
                {
                    ViewData["ErrorMessage"] = "Error";
                }
                return RedirectToAction("AgreementList");
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
                return View("AgreementList");
            }

        }
        //// GET: EditAgreement
        public ActionResult AgreementEdit(int AgreementKey)
        {
            try
            {
                FillStatus();
                List<AgreementModel> AgreementList = null;
                AgreementModel Agreementlist = new AgreementModel();
                Agreementlist = __aGreementService.GetDataViewEdit(AgreementKey);
                return View(Agreementlist);
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
            }
            return View();

        }
        [HttpPost]
        public ActionResult AgreementEdit(int AgreementKey, AgreementModel collection)
        {
            try
            {
                    Int64 value = 0;
                collection.AgreementDate = Convert.ToDateTime(collection.AgreementDates);

                    value = __aGreementService.AgreementEdit(collection);
                    if (value == 0)
                    {
                        TempData["SuccessMessage"] = "Record has been  updated successfully.";
                    }
                    else
                    {
                        ViewData["ErrorMessage"] = "Error";
                    }
                AgreementModel Agreementlist = new AgreementModel();
                Agreementlist = __aGreementService.GetDataViewEdit(AgreementKey);
              
                return RedirectToAction("AgreementView", new { AgreementKey });
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
                return RedirectToAction("AgreementView", new { AgreementKey });
            }
        }
        public ActionResult Delete(Int32 AgreementKey)
        {
            try
            {

                bool value = false;
                value = __aGreementService.Delete(AgreementKey);
                if (value == true)
                {
                    TempData["Sucessmessage"] = "Record has been deleted successfully.";
                }
                else
                {
                    ViewData["Errormessage"] = "Error";
                }
                return RedirectToAction("AgreementList");
            }

            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
                return RedirectToAction("AgreementList");
            }

        }
        public void FillStatus()
        {
            try
            {
                var lststatus = new List<SelectListItem>()
            {
              new SelectListItem{ Value="0",Text="Choose one",Selected=true},
              new SelectListItem{ Value="1",Text="Active"},
              new SelectListItem{ Value="2",Text="Inactive"},
            };
                ViewBag.lststatus = lststatus;
            }
            catch (Exception ex)
            {
                Common.Error.WriteErrorsToFile(ex.Message.ToString());
            }
           
        }
    }
}

AssociationBids.Portal/Views/Agreement/AgreementAdd.cshtml
@model AssociationBids.Portal.Model.AgreementModel

@{
    ViewBag.Title = "AgreementAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AgreementAdd</h2>
<!-- app-content-->
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<div class="app-content  my-3 my-md-5">
    <div class="side-app">

        <!-- page-header -->
        <div class="page-header">
            <ol class="breadcrumb">
                <!-- breadcrumb -->
                <li class="breadcrumb-item"><a href="AgreementList">Agreements</a></li>
                <li class="breadcrumb-item active" aria-current="page">Add Agreements</li>

            </ol><!-- End breadcrumb -->
        </div>
     <div class="alert alert-danger" id="Error" style="display:block; margin-top: 20px;">
        <strong><span class="errormessage"></span></strong>
    </div>

    @using (Html.BeginForm("AgreementAdd", "Agreement", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            <div class="col-12">
                <div class="card">

                    <div class="card-body">

                        <div class="form-div">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="form-label">
                                            Title
                                            @Html.ValidationMessageFor(model => model.Title, "*", new { @class = "text-danger" })
                                        </label>
                                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @tabindex = "1", autocomplete = "off", placeholder = "Agreement Title" } })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="form-label">
                                            Agreement Date
                                            @Html.ValidationMessageFor(model => model.AgreementDate, "*", new { @class = "text-danger" })
                                        </label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fa fa-calendar tx-16 lh-0 op-6"></i>
                                                </div>
                                            </div>
                                          
                                            @Html.EditorFor(model => model.AgreementDate, new { htmlAttributes = new { @class = "form-control fc-datepicker", @tabindex = "1", autocomplete = "off", placeholder = "MM/DD/YYYY" } })
                                          
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="form-label">
                                            Status
                                            @Html.ValidationMessageFor(model => model.Status, "*", new { @class = "text-danger" })
                                        </label>
                                        @Html.DropDownListFor(model => model.Status, new SelectList(ViewBag.lststatus, "Value", "Text"), new { @data_rel = "Choose_one", @class = "form-control", placeholder = "Please Select..." })

                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-label">
                                            Description
                                            @*@Html.ValidationMessageFor(model => model.Description, "*", new { @class = "text-danger" })*@
                                        </label>
                                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Description", @tabindex = "1" })
                                    </div>
                                </div>

                            </div><!-- end of row -->
                            <hr />

                            <div class="button-row d-flex mt-4">
                                <a href="@Request.UrlReferrer" class="btn btn-default" title="Cancel">Cancel</a>
                                @*<button class="btn btn-info ml-auto js-btn-next" id="btnsubmit" type="button" title="Next">Next <i class="fe fe-chevron-right"></i></button>*@
                                <input t class="btn btn-primary ml-auto" id="btnsubmit" type="submit" onclick="return validation()" title="Save" value="Save" /><i class="fa fa-loppy-o"></i>
                            </div>
                        </div><!-- end of form-div  -->
                    </div><!--end of card body -->
                </div>
            </div>
        </div>

    }
    <!-- Right-sidebar-->
    <!--footer-->
    <footer class="footer">
        <div class="container">
            <div class="row align-items-center flex-row-reverse">
                <div class="col-lg-12 col-sm-12   text-center">
                    Copyright © 2020 Association Bids. All rights reserved.
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer-->

</div>
</div>

<!-- Custom js-->
<script src="../assets/js/custom.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        //$("#Agree").closest('li').addClass('active');
        //$("#Agree1").addClass('active');
        SetActiveMenu($("#Agree"), false);
        $(".advance_search").click(function () {
            $("#advancesearch3").toggle(500);
        });
        $(".overlayclose").click(function () {
            $("#advancesearch3").hide();
        });
    });

  
    //$(function () {
    //    $('#SelectedDate').datepicker({
    //        changeMonth: true,
    //        changeYear: true,
    //        format: "dd/mm/yyyy",
    //        language: "tr",
    //        maxDate: 0
    //    });
    //});

    $(document).ready(function () {
        $('#loader').show();
        $('.errormessage').html('');
        $('#Error').hide();

        $('#loader').hide();

    });
    function validation() {
        //debugger;
     
        $('#loader').show();
        $('.errormessage').html('');

        if ($('#Title').val() == "") {
            $('.errormessage').html('Please Enter Title.');
            $('#Error').show();
            $('#Title').focus();
            $(window).scrollTop(0);
            return false;
        }
        if ($('#Status').val() == "0") {
            $('.errormessage').html('Please Select Status.');
            $('#Error').show();
            $('#Status').focus();
            $(window).scrollTop(0);
            return false;
        }
        debugger;
        
        if ($('#AgreementDate').val() == "") {
            $('.errormessage').html('Please Enter Agreement Date.');
            $('#Error').show();
            $('#AgreementDate').focus();
            $(window).scrollTop(0);
            return false;
        }
        
        //var valueDate = document.getElementById('AgreementDate').value;
        //if (valueDate == null || valueDate == '') {
        //    $('.errormessage').html('Please Enter Agreement Date.');
        //    $('#Error').show();
        //    $('#AgreementDate').focus();
        //    $(window).scrollTop(0);
        //    return false;
        //}
      
        //if ($('#Description').val() == "") {
        //    $('.errormessage').html('Please Enter Description.');
        //    $('#Error').show();
        //    $('#Description').focus();
        //    $(window).scrollTop(0);
        //    return false;
        //}
        $('#loader').hide();
        window.location.href = 'AgreementView?AgreementKey=' + $("#AgreementKey").val();
        return true;
    }

    function Clear() {

        document.getElementById("Title").value = "";
        document.getElementById("AgreementDate").value = "";
        document.getElementById("Description").value = "";
        document.getElementById("Status").value = "Please Select";
        $('.field-validation-error').html("");
    }
</script>

AssociationBids.Portal/Views/Agreement/AgreementEdit.cshtml
@model AssociationBids.Portal.Model.AgreementModel

@{
    ViewBag.Title = "AgreementEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AgreementEdit</h2>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<div class="app-content  my-3 my-md-5">
    <div class="side-app">

        <!-- page-header -->
        <div class="page-header">
            <ol class="breadcrumb">                <!-- breadcrumb -->
                <li class="breadcrumb-item"><a href="AgreementList">Agreements</a></li>
                @*<li class="breadcrumb-item"><a href="~/Agreement/AgreementView">Agreemnet Details</a></li>*@
                <li class="breadcrumb-item active" aria-current="page">Edit Agreements</li>

            </ol><!-- End breadcrumb -->

        </div>

        <div class="alert alert-danger" id="Error" style="display:block; margin-top: 20px;">
            <strong><span class="errormessage"></span></strong>
        </div>
        @using (Html.BeginForm("AgreementEdit", "Agreement",  FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="row">
          
                <div class="col-12">
                    <div class="card">

                        <div class="card-body">
                            @*<div class="row">
                                <div class="col-md-12">
                                    <div class="text-right"><a href="#" role="button" id="btndelete" class="btn btn-icon btn-danger" style="margin-right:10px;"><i class="fe fe-trash"></i> Delete</a></div>
                                   
                                </div>
                            </div>*@
                            
                            <div class="form-div">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="form-label">
                                                Title
                                                @Html.ValidationMessageFor(model => model.Title, "*", new { @class = "text-danger" })
                                            </label>
                                            @Html.HiddenFor(model => model.AgreementKey)
                                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @tabindex = "1", autocomplete = "off", placeholder = "Title" } })
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="form-label">
                                                Agreement Date
                                                @Html.ValidationMessageFor(model => model.AgreementDate, "*", new { @class = "text-danger" })
                                            </label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <i class="fa fa-calendar tx-16 lh-0 op-6"></i>
                                                    </div>
                                                </div>
                                                @Html.EditorFor(model => model.AgreementDates, new { htmlAttributes = new { @class = "form-control fc-datepicker", @tabindex = "1", autocomplete = "off", placeholder = "MM/DD/YYYY" } })

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="form-label">
                                                Status
                                                @Html.ValidationMessageFor(model => model.Status, "*", new { @class = "text-danger" })
                                            </label>
                                            @Html.DropDownListFor(model => model.Status, new SelectList(ViewBag.lststatus, "Value", "Text"), new { @data_rel = "Choose_one", @class = "form-control", placeholder = "Please Select..." })
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="form-label">
                                                Description 
                                            </label>
                                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Description", @tabindex = "1" })
                                        </div>
                                    </div>

                                </div><!-- end of row -->
                                <hr />

                                <div class="button-row d-flex mt-4">
                                    @*<a href="" id="btnCancel" class="btn btn-default" title="Cancel">Cancel</a>*@
                                    <div class="col-md-2 left">
                                        <div class="text-left"><a href="#" role="button" id="btnCancel" class="btn btn-default" style="margin-right:10px;"> Cancel</a></div>
                                    </div>
                                    <div class="col-md-9 right">
                                        <div class="text-right">
                                            <input t class="btn btn-primary ml-auto" id="btnsubmit" type="submit" onclick="return validation()" title="Update" value="Update" /><i class="fa fa-loppy-o"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-0 right">
                                        <div class="text-right">
                                            <a href="#" role="button" id="btndelete" class="btn btn-icon btn-danger" style="margin-right:10px;"><i class="fe fe-trash"></i> Delete</a>
                                        </div>

                                    </div>
                                </div>

                                </div><!--end of card body -->
                        </div>
                    </div>
                </div>
            </div><!--End side app-->
        }

        <!-- Right-sidebar-->
        <!--footer-->
        <footer class="footer">
            <div class="container">
                <div class="row align-items-center flex-row-reverse">
                    <div class="col-lg-12 col-sm-12   text-center">
                        Copyright © 2020 Association Bids. All rights reserved.
                    </div>
                </div>
            </div>
        </footer>
        <!-- End Footer-->
        <!-- End Page -->
        <!-- Back to top -->
        <!-- Custom js-->
        <script src="../assets/js/custom.js"></script>



        <script>
          

            $(document).ready(function () {
                //$("#Agree").closest('li').addClass('active');
                //$("#Agree1").addClass('active');
                SetActiveMenu($("#Agree"), false);
                $('#loader').show();
                $('.errormessage').html('');
                $('#Error').hide();

                $('#loader').hide();

            });
            function validation() {
                //debugger;
                
                $('#loader').show();
                $('.errormessage').html('');

                if ($('#Title').val() == "") {
                    $('.errormessage').html('Please Enter Title.');
                    $('#Error').show();
                    $('#Title').focus();
                    $(window).scrollTop(0);
                    return false;
                }
                if ($('#Status').val() == "0") {
                    $('.errormessage').html('Please Select Status.');
                    $('#Error').show();
                    $('#Status').focus();
                    $(window).scrollTop(0);
                    return false;
                }

                if ($('#AgreementDate').val() == "") {
                    $('.errormessage').html('Please Enter Agreement Date.');
                    $('#Error').show();
                    $('#AgreementDate').focus();
                    $(window).scrollTop(0);
                    return false;
                }

                //if ($('#Description').val() == "") {
                //    $('.errormessage').html('Please Enter Description.');
                //    $('#Error').show();
                //    $('#Description').focus();
                //    $(window).scrollTop(0);
                //    return false;
                //}
                $('#loader').hide();

                window.location.href = 'AgreementView?AgreementKey=' + $("#AgreementKey").val();
                return true;
            }

           
            function Clear() {

                document.getElementById("Title").value = "";
                document.getElementById("AgreementDate").value = "";
                document.getElementById("Description").value = "";
                document.getElementById("Status").value = "Please Select";
                $('.field-validation-error').html("");
            }
           
            
            $("#btnCancel").click(function () {
                window.location.href = 'AgreementView?AgreementKey=' + $("#AgreementKey").val();
            });

            $("#btndelete").click(function () {
                if (confirm('Are you sure you want to delete this record?')) {
                    window.location.href = 'Delete?AgreementKey=' + $("#AgreementKey").val();
                    return true;
                }
                else {
                    return false;
                }
            });
            $(document).ready(function () {
                //debugger;
                $("#ddlload").hide();
            });


        </script>

       